### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by SisterLemon7** [Srchronotrigger/Message-2Harkinian#1]
Upon trying to build the m2h-betaV0.1.jar file, I get an exception. I'm using JDK 22. Here's the exception.

Exception in thread "Thread-0" java.lang.IllegalArgumentException: input == null!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1356)
        at com.message_2harkinian.screen.CustomPanel.<init>(CustomPanel.java:67)
        at com.message_2harkinian.screen.CustomWindow.createAndShowGUI(CustomWindow.java:19)
        at com.message_2harkinian.screen.CustomWindow.run(CustomWindow.java:39)
        at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by Srchronotrigger** [comment]
Hi, the assets folder must be on project root directory, so if you are using an IDE, put the assets folder on compiled classes folder, see the tree:
```
C:.
├───assets
│       background.png
│       blank.png
│       bloggerLogo.png
│       configsButtonClicked.png
│       configsButtonNonClicked.png
│       exitButtonClicked.png
│       exitButtonNonClicked.png
│       githubLogo.png
│       minimizeButtonClicked.png
│       minimizeButtonNonClicked.png
│       selectFileButtonClicked.png
│       selectFileButtonNonClicked.png
│       startButtonClicked.png
│       startButtonNonClicked.png
│       VersionLogoClicked.png
│       VersionLogoNonClicked.png
│
└───com
    └───message_2harkinian
        ├───main
        │       HexWriter.class
        │       Interpreter.class
        │       Main.class
        │
        ├───screen
        │       CustomPanel$1.class
        │       CustomPanel$2.class
        │       CustomPanel$3.class
        │       CustomPanel$4.class
        │       CustomPanel.class
        │       CustomWindow.class
        │
        └───utils
                Constants.class
```             
if you already build the .jar file just put the assets folder on the same directory and execute the .jar file:

```
C:.
│   m2h-betaV0.1.jar
└───assets
        background.png
        blank.png
        bloggerLogo.png
        configsButtonClicked.png
        configsButtonNonClicked.png
        exitButtonClicked.png
        exitButtonNonClicked.png
        githubLogo.png
        minimizeButtonClicked.png
        minimizeButtonNonClicked.png
        selectFileButtonClicked.png
        selectFileButtonNonClicked.png
        startButtonClicked.png
        startButtonNonClicked.png
        VersionLogoClicked.png
        VersionLogoNonClicked.png
```

**Comment by SisterLemon7** [comment]
Yep, putting the jar file in the root folder fixed it. Thank you, I'll be closing this issue now.

**Comment by Srchronotrigger** [comment]
> Yep, putting the jar file in the root folder fixed it. Thank you, I'll be closing this issue now.

You are welcome, i'm glad it worked out, good luck with your mods! God bless you.
